version: 0.2

phases:
 install:
  runtime-versions:
   docker: 18
 pre_build:
  commands:
   - $(aws ecr get-login --no-include-email --region us-east-1)
 build:
  commands:
   - cd pensionerDisbursementMicroservice
   - mvn compile
   - mvn package
   - docker build -t pension/disburse .
   - docker tag pension/disburse 885843804602.dkr.ecr.us-east-1.amazonaws.com/pension-disburse:latest
 post_build:
  commands:
   - docker push 885843804602.dkr.ecr.us-east-1.amazonaws.com/pension-disburse:latest
   - printf '[{"name":"pension-disburse-container","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-1.amazonaws.com/pension-disburse:latest > taskdefinition.json
artifacts:
 files:
  - pensionerDisbursementMicroservice/taskdefinition.json