server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /db
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    
  main:
    allow-circular-references: true
     

  
